version: '3.0'

#Docker Networks
networks:
  currency:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local

# Workflow
services:
  service.currency:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php_8_1
      - postgres
    networks:
      - currency

  php_8_1:
    build:
      context: .
      dockerfile: ./docker/php/8.1/Dockerfile
    container_name: php_8_1
    volumes:
      - ./src:/var/www/html:delegated
      # Enable xdebug
      - ./docker/php/8.1/xdebug.ini:/usr/local/etc/php/8.1/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "9003:9003"
    networks:
      - currency
    extra_hosts:
      - 'currency.api:192.168.65.2'
      - 'host.docker.internal:host-gateway'
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/postgresql/:/docker-entrypoint-initdb.d/
    networks:
      - currency
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - currency